site_name: Tulipan
site_description: 'Documentation for Tulipan.js, a simple and progressive, JavaScript Framework for building Single Page Applications on the web.'
site_url: 'http://tulipan-documentation.readthedocs.io'
site_author: https://github.com/carrasquel/tulipan-documentation/graphs/contributors
repo_url: http://github.com/carrasquel/tulipan
remote_branch: master
nav:
  - Getting Started:
    - Home: index.md
    - Getting Started: started/started.md
  - User Guide:
    - Bindings: guide/bindings.md
    - Properties: guide/properties.md
    - Renderings: guide/renderings.md
    - Filters: guide/filters.md
    - Web Requests: guide/requests.md
    - Routing: guide/routing.md
    - Storing: guide/storing.md
    - User Interaction: guide/interactions.md 

theme: 
  name: material

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/tulipan.min.js
  - javascripts/demo.js
  - javascripts/book.js

extra:
  social:
    - type: 'github'
      link: 'https://github.com/carrasquel'

google_analytics:
  - 'UA-125411854-4'
  - 'auto'

plugins:
    - pdf-export:
        combined: true

markdown_extensions:
  - codehilite